"use strict";
let place = ["burj khalifa", "Nagara falls", "china glass bridge", "sawat", "calafornia glass beach"];
console.log("original array \n");
console.log(place);
let newplace = Array.from(place);
//had to use duplicate array since localecompare effects original array
let alphasortedarray = place.sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));
console.log("alphabetically ordered array \n");
console.log(alphasortedarray);
console.log("original array \n");
console.log(newplace);
let reversedalphasortedarray = place.sort((a, b) => b.localeCompare(a));
console.log("reversed alphabetically ordered array \n");
console.log(reversedalphasortedarray);
console.log("original array \n");
console.log(newplace);
place.reverse();
console.log("array reversed \n");
console.log(place);
place.reverse();
console.log("array reversed again so its back to normal \n");
console.log(place);
place.sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));
console.log("the order of the original array has been set to alphabetical \n");
console.log(place);
place.sort((a, b) => b.localeCompare(a, undefined, { sensitivity: "base" }));
console.log("the order of the original array has been set to reversed alphabetical \n");
console.log(place);
console.log("now the original array has been saved in reversed alphabetical order \n");
